print("Hello World!")
print("Hello there!")
print("General Kenobi!")
print("Har jeg skjønt det?")
print("Hei Olivir")
print("Kjører på koden min")
print("Kjører dette Oliver?")
print("Yes")
def printHelloWorld():
    print("Hello World")
print("Boller is back")
print("Hei Astrid, du er søt, ser du dette?")